import type { Metadata } from 'next'

// These styles apply to every route in the application
import '../public/assest/cssFile/globals.css'
import 'react-toastify/dist/ReactToastify.css';
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}